version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm_and_yarn:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github_actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
